### ISSUE TITLE
Please improve swagger-tools migration documentation

### ISSUE THREAD

**Issue by robaca** [isa-group/oas-tools#120]
It's not clear from the documentation that all middlewares returned by the `initializeMiddleware` function are now no-ops and the middlewares are already registered beforehands.

Please also document missing features compared to swagger-tools (like response validation).

**Comment by raffrearaUS** [comment]
We have added a new section at the end of the migration instructions. We will be updating the list of differences with swagger-tools as issues are created and solved. Thanks for the suggestion!
