### ISSUE TITLE
express error handling middleware circumvented 

### ISSUE THREAD

**Issue by Fedelaus** [isa-group/oas-tools#128]
It appears when using oas-tools, the conventional express based error handling is not picking up errors thrown in controllers.

The below snippet is my controller method, just exists to throw an error.

```ts
export function getSensors(request: Request, response: Response, next) {
    next(new Error('error'));
}
```

I'm then using the following:

```ts
oasTools.initializeMiddleware(oasDoc, app, function(middleware) {
	app.use(function(err, req, res, next) {
		console.log('stepped into here');
	});
	// Start the application listening on the provided port.
	app.listen(2000);
});
```

Upon raising my error in `getSensors`, I am expecting my `stepped into here` to log out, but instead the error just comes out.

The setup above should be similar to the below example, which acts as expected

```js

import express from 'express';

const app = express();

app.get('/test', (req, res, next) => {
    next(new Error('hello'));
})

app.use(function(err, req, res, next) {
    console.log('error', err);
})

app.listen(2000)
```

This will heavily affect how we design controllers and other parts of our API - is this an intended effect, have I done something wrong or is this easily fixed?

**Comment by Fedelaus** [comment]
The issue here was my understanding of what `initializeMiddleware` was doing.

To get it working from my broken example, I simply had to move the `app.use` to below the initialize.
This is because `callback` is called before `registerPaths` internally.

```
oasTools.initializeMiddleware(oasDoc, app, function(middleware) {
	// Start the application listening on the provided port.
	app.listen(2000);
});

app.use(function(err, req, res, next) {
	console.log('stepped into here');
});
```

**Comment by Chetan07j** [comment]
Hi, @Fedelaus this even does not work for me, tried it placing at all possible places, still not working.

**Comment by Fedelaus** [comment]
@Chetan07j `not working` requires further explanation!

Please post some code, I'm not a project maintainer but am happy to have a look at the problem you're having. I've seen the other issue you have opened but the code snippet provided is too small - we need to see the rest of your setup around oas-tools.

If you could provide the source code where you initialize your middleware, that would help.

I would recommend closing off your other issue and keeping the discussion around middleware within this issue for the sake of not duplicating things.

**Comment by Chetan07j** [comment]
Hi @Fedelaus, thanks for you response on same
here is my code 

```javascript
const swaggerTools = require('oas-tools');
const express = require('express');
const path = require('path');
const fs = require('fs');
const yaml = require('js-yaml');

require('express-async-errors');

const app = express();

const swaggerDoc = yaml.safeLoad(fs.readFileSync(path.join('./api/swagger/swagger.yaml'), 'utf8'));

const options = {
  controllers: path.join(__dirname, './api/controllers'),
  loglevel: 'info',
  strict: true,
  validator: true,
  docs: {
    apiDocs: '/api-docs',
    apiDocsPrefix: '',
    swaggerUi: '/docs',
    swaggerUiPrefix: '',
  },
};

swaggerTools.configure(options);

swaggerTools.initializeMiddleware(swaggerDoc, app, (middleware) => {
  app.use(middleware.swaggerMetadata());
  app.use(middleware.swaggerValidator());
  app.use(middleware.swaggerUi());

  app.use((err, req, res, next) => {
    console.log('-----Something broke!---', err)
    res.status(500).send('Something broke!')
  })

  const port = process.env.PORT || 3001;
  const server = app.listen(port);
  app.close = () => server.close();
});

// TRIED "errorHandler" HERE AS WELL
module.exports = app;

```
I tried putting error handler at all possible place, but still not working.

**Comment by Chetan07j** [comment]
I want to implement something like, 
I have removed catch from all controllers, and want to catch all errors at one plcae instead adding catch everywhere.
Can you suggest me something on this.

**Comment by Fedelaus** [comment]
@Chetan07j 

I have a query. 

```

**Comment by Fedelaus** [comment]
Closing this as I believe it still works. Please @ me if you still require assistance.
