### ISSUE TITLE
snyk did not release 2.0.0 yet breaks npm install

### ISSUE THREAD

**Issue by shuat** [isa-group/oas-tools#166]
pull request #154 from isa-group/greenkeeper/snyk-2.0.0 broke the code
Why was this merged in? Look here https://www.npmjs.com/package/snyk
The latest version is 1.217.3

**Comment by raffrearaUS** [comment]
Sorry about this, I don't really understand why Greenkeeper created that PR. It has been reverted in #170 and npm install works again.
