### ISSUE TITLE
HEAD and PATCH methods should be supported by OAS-Auth

### ISSUE THREAD

**Issue by adambordas** [isa-group/oas-tools#172]
https://github.com/isa-group/oas-tools/blob/573c52907807de53271f9d14c7b70d5f5569afc1/src/middleware/oas-auth.js#L60-L72

OAS-Auth only supports GET, POST, PUT and DELETE methods for permission checking. HEAD and PATCH should also be included, because according to the specifications:
* The HEAD method asks for a response identical to that of a GET request, but without the response body.
* The PATCH method is used to apply partial modifications to a resource.

https://developer.mozilla.org/en-US/docs/Web/HTTP/Methods

Based on that, HEAD should require 'read' permission and PATCH should require 'update' permisison.

**Comment by maxproske** [comment]
@raffrearaUS This has been done since September 2019, and this would be really nice to have. Can 2.1.8 please be released with the enhancements it has so far?
