### ISSUE TITLE
Where to define a custom Middleware to intercept RouterMiddleware response?

### ISSUE THREAD

**Issue by omarquina-areuin** [isa-group/oas-tools#199]
Hi. 
My controllers respond with raw data, I have a global response middleware which takes each controller response and wrap it, in a JSON "data block" at body response:
**{
  "timestamp": xxxxxx,
  "status": 200,  
  "data": { controller response Object } 
}**
I'm using express-mung, to format general response.
I define my general middleware before to call **initializeMiddleware**. 
I've tried to set it, at the callback function, but the paths are loaded after the callback is called.
I've tried to define my middleware, after initializeMiddleware was finished, but the RouterMiddleware remain the last middleware who is called, skipping my default middleware. I don't know what i'm doing wrong or if I misunderstood something at documentation. Thanks in advance

**Comment by omarquina-areuin** [comment]
This is a ExpressJS topic, not an oas-tools issue. I solve it, overwriting the res.send() function in an app.use() middleware before to configure oas-tools.

**Comment by Chetan07j** [comment]
Hi, @omarquina-areuin how did you solved this issue, can share it please?
