### ISSUE TITLE
Express Global Excepion Handler Not Working

### ISSUE THREAD

**Issue by Chetan07j** [isa-group/oas-tools#205]
Hi,

I want to add Global Exception Handler in my Node application, so I am trying to add below code:

```js
app.use((err, req, res, next) => {
    console.log('-----Something broke!---', err)
    res.status(500).send('Something broke!')
  })
```
but this function is not at all executed.

Can you please help me to make global exception handling work?

**Comment by Fedelaus** [comment]
Duplicate of https://github.com/isa-group/oas-tools/issues/128 - recommend closing.

**Comment by Chetan07j** [comment]
closing because of duplicate
