### ISSUE TITLE
Linked from 'awesome' lists

### ISSUE THREAD

**Issue by dani8art** [isa-group/oas-tools#29]
Hi, 

First, I'd like to congrats you, these two repositories: [oas-generator](https://github.com/isa-group/oas-generator) and [oas-tools](https://github.com/isa-group/oas-tools) are really amazing projects, I'm sure they will be so useful in my future projects. 

In addition, I thought that could be a good idea having them in the 'awesome' lists which exist across GitHub in order to increment the visibility of them. Here I would like to give you guys these two that I've found:

- [https://github.com/APIs-guru/awesome-openapi3](https://github.com/APIs-guru/awesome-openapi3)

- [https://github.com/marmelab/awesome-rest](https://github.com/marmelab/awesome-rest)

Cheers.

**Comment by pafmon** [comment]
Thanks Dani! :-)  It's a great idea! We'll sure go for it!

**Comment by raffrearaUS** [comment]
Thanks for your suggestion! Pull requests for both tools have been opened in those two lists, and, in fact, oas-generator can be already found in the first one!
I'm closing this issue since I don't think we need to wait until every pull request has been merged to do it.

**Comment by dani8art** [comment]
Cool! We will wait for stars and forks! 😉
