### ISSUE TITLE
[SUGGESTION] Problem with default exports "Controller X does not have method Y"

### ISSUE THREAD

**Issue by webnator** [isa-group/oas-tools#372]
**Is your feature request related to a problem? Please describe.**
When using default export in a controller the library is not able to retrieve the requested method, and instead throws an error of Problem when exporting from default module "Controller X does not have method Y"

Currently it only supports named exports

**Describe the solution you'd like**
Support both named exports and a default export that contains the method requested

**Describe alternatives you've considered**
I can of course do named exports for each method in my module, but that would be a nightmare when adding new methods

**Additional context**
I should mention here that I'm using awilix library for dependency injection, which means that I don't have a "direct" module definition. So my controller file looks something like this

```
import container from 'container.js';

const myController = container.resolve('myController');

export default myController;
```
So, I could do something like
```
export const method1 = myController.method1;
export const method2 = myController.method2;
export const method3 = myController.method3;
...
```
But you see how it'd become hell to maintain really quick

**Comment by alesancor1** [comment]
Currently merged to develop branch. Will be released in the next version.
