### ISSUE TITLE
[BUG] customHandler for errors is not working as expected

### ISSUE THREAD

**Issue by webnator** [isa-group/oas-tools#374]
## **Describe the bug**
Not really sure if a bug or suggestion but here it goes.
According to the [docs](https://oas-tools.github.io/docs/features/error-handling#extending-the-handler) one can specify a custom error handler in the config to extend the functionality of error handling.

In my case, the responses of my API need to be formatted in a very specific way, so, the base error handler for when (in example) a bearer token is required but not provided, is insufficient.

I thought this was the case covered by the customHandler for errors, but now I see it's not working. If I get a SecurityError, I don't have any control over how the response looks

## **To Reproduce**
1. Set up an API endpoint that has a BearerAuth security specified
2. Configure a customHandler for errors in the config
3. Call the endpoint without specifying any auth header
4. The customHandler is not called, and instead a generic response is thrown

## **Expected behavior**
The customHandler should be called overriding any generic response

**Comment by alesancor1** [comment]
Merged into the develop branch, will be available in the next release.

**Comment by caarmen** [comment]
Was this released?
