### ISSUE TITLE
[SUGESTION] Add support for mutualTLS security handler

### ISSUE THREAD

**Issue by john-macedo** [isa-group/oas-tools#377]
New to openapi 3.1 specification is the ability to use mutualTLS as a valid security scheme. While the current version of oas-tools correctly validates an openapi specification with mutualTLS as a security scheme and even requires a security handler for it (when configured with security enabled), if we later receive a request, the middleware throws an 'UnsupportedError "Security scheme ${secName} is invalid or not supported."'

This feature would add support for mutualTLS security handlers by extracting the TLS peer (client side) TLS certificate associated with an incoming request and invoking the corresponding security handler with the certificate as the sole parameter.  If no certificate exists or if the connection is not a TLS connection in the first place then an empty or null certificate parameter is passed in to the security handler. In order to receive a certificate in the first place, an https server would have to be created and configured to requestCert and optionally rejectUnauthorized certs (based on the cert chain alone). 

Once passed a certificate, the security handler would then be able to examine the provided cert in order to decide whether to allow access to that specific client based on whatever criteria it chooses to implement.

**Comment by alesancor1** [comment]
Merged to the develop branch. Will be available in the next release.
