### ISSUE TITLE
Update readme file to reflect all new changes

### ISSUE THREAD

**Issue by raffrearaUS** [isa-group/oas-tools#42]
The readme file has not been updated since the last version was released. Some new features should be explained in it.

**Comment by antgamdia** [comment]
Another option is using https://readthedocs.org/  or https://docsify.js.org/ or https://daux.io/. Thx for the suggestion @dani8art  :)

**Comment by raffrearaUS** [comment]
Thanks for all these suggestions! Since this issue was meant for the readme file, I will be closing it as soon as it has been updated. However, I have already opened a new issue (#45) to take this suggestions into account.
