### ISSUE TITLE
Provide json schema for error responses

### ISSUE THREAD

**Issue by wingedfox** [isa-group/oas-tools#44]
Hi,

As long as you report errors right from the framework, please define json schema of these erorrs in order to include it into application API.
It's pretty safe to define json schema, there's https://www.npmjs.com/package/speccy tool for json schema to open api conversion.
If you need a help with schema, don't hesitate to ask me.

**Comment by raffrearaUS** [comment]
I have included a JSON Schema definition in the readme file, [here](https://github.com/isa-group/oas-tools/tree/devel#4-errors). Is this what you are suggesting?
Thanks four your feedback!

**Comment by wingedfox** [comment]
Thank you for the updated documentation.

It would be great to have an exportable entity to refer to from the client code as well, i.e.
```yaml
$ref: ../../../node_modules/oas-tools/schemas/validation-errors.json
```
or even a have post-install script to copy schemas from oas-tools.
Copy-paste can't help here just because it prevents automatic schema update.

Btw, please take a look at: https://github.com/wingedfox/reviews-service-demo, I'd like to maintain it as a template for my future projects and automatic schema updates are vital there.

**Comment by raffrearaUS** [comment]
A JSON file with the same name and path you have suggested has been included. Thanks for the tip!
This issue can now be closed, right?
