### ISSUE TITLE
oasTools securityFile callback doesn't allow for async validation function

### ISSUE THREAD

**Issue by vobu** [isa-group/oas-tools#81]
Hi,

when using `oasSecurity` like
```js
oasTools.configure({
  // ...
  oasSecurity: true,
  securityFile: {
    <secScheme>: async (req, secDef, key, next) => { return next() }
  }
});
```
the framework errors out with 
```
Error: No handler was specified for security scheme ApiKeyAuth
    at async.map (/path/to/proj/node_modules/oas-tools/src/middleware/oas-security.js:109:45)
```

This seems due to an outdated version of `lodash-compat` being used for validating the ` <secScheme>` cb in https://github.com/isa-group/oas-tools/blob/master/src/middleware/oas-security.js#L105 - see also lodash issue over at https://github.com/lodash/lodash/issues/3603

Could you please bump `lodash-compat` to a more current version in order to allow async callbacks for security validations?

Thanks in advance!

**Comment by raffrearaUS** [comment]
Sadly, `lodash-compat` is no longer maintained, and we are already using the latest version. Nonetheless, this issue has been fixed following the advice on the lodash issue you linked.
