### ISSUE TITLE
[Bug]  code EISGIT cause '*.git ' inside the  module -oas-tools "2.1.5"

### ISSUE THREAD

**Issue by engiwip** [isa-group/oas-tools#99]
Hi all , 

Please remove the *.git inside the node_module before publishing the package
cause :
**npm ERR! code EISGIT**

npm ERR! git Refusing to remove it. Update manually,
npm ERR! git or move it out of the way first.

many thanks

**Comment by pjmolina** [comment]
Adding PR #101 to try to fixing it, Makes sense to you @engiwip ?

**Comment by engiwip** [comment]
> Adding PR #101 to try to fixing it, Makes sense to you @engiwip ?

great.

**Comment by Fedelaus** [comment]
@pjmolina it appears that `2.1.5` is the published npm version which still has the `.git` folder in it - meaning anyone installing this from npm currently will be getting a broken version (as it stops further `npm install`s).

**Comment by mrcdb** [comment]
When is the `oas-tools` version on npm going to be updated?

**Comment by liranms** [comment]
any change you can release a new version without the .git?
currently npm is really pissed of by that and for any npm install we have to delete the .git subdir manually

**Comment by raffrearaUS** [comment]
Version 2.1.6 has been released and this issue is now fixed. I'm really sorry for the inconvenience.
